### ISSUE TITLE
Learning TODO

### ISSUE THREAD

**Issue by ChrisVilches** [ChrisVilches/poller#1]
- [ ] Improve project structure (learn how to split the app into modules correctly).
- [ ] Learn and use "guards".
- [ ] Learn and use "pipes". Create my own pipes.
- [ ] Similar to pipes, add some validations (https://docs.nestjs.com/techniques/validation).
- [ ] Learn article about dependency injection (from Angular website).
- [ ] Read the "Fundamentals" section in the NestJS documentation site.
- [ ] Try a few more points in the "Techniques" section.
- [ ] Add tests. At least test what can be tested easily, such as the `rules` folder.
- [ ] Read the Overview section. I know most of it except [Exception filters](https://docs.nestjs.com/exception-filters)
- [ ] Solve `TODO` comments.
